server:
  port: 8080
  servlet:
    context-path: /vidsonet

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/vidsonetest"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
file:
  upload-dir: "C:\\Users\\PC\\OneDrive\\Desktop\\uploads"
jwt:
  signerKey: "YYzrYVGsu1A65dvMxYP1W+d2LcC7fAFTLoa+5kT9rj5dDNL77BPUyEsMKbGNN2G7"
channel:
  profile-image-url: "C:\\Users\\PC\\OneDrive\\Pictures\\kevin-sanjaya3.jpg"
  banner-image-url: "C:\\Users\\PC\\OneDrive\\Pictures\\banner1.jpg"
#outbound:
#  identity:
#    client-id: "<clientId>"
#    client-secret: "<clientSecret>"
#    redirect-uri: "http://localhost:3000/authenticate"
#
#jwt:
#  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
#  valid-duration: 3600 # in second
#  refreshable-duration: 36000 # in seconds
