server:
  port: 8080
  servlet:
    context-path: /vidsonet

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/vidsonet"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
file:
  upload-dir: "C:\\Users\\PC\\OneDrive\\Desktop\\uploads"
#outbound:
#  identity:
#    client-id: "<clientId>"
#    client-secret: "<clientSecret>"
#    redirect-uri: "http://localhost:3000/authenticate"
#
#jwt:
#  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
#  valid-duration: 3600 # in second
#  refreshable-duration: 36000 # in seconds
